Increase testing
- Add a Host abstraction to enable unit testing.

- Add a bunch of unit tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -135,7 +135,6 @@ jobs:
         with:
           enable-sccache: true
           rust-toolchain: RUST_NIGHTLY
-          rust-components: miri
           cargo-tools: CARGO_UDEPS_VERSION, CARGO_CAREFUL_VERSION, CARGO_NEXTEST_VERSION
 
       # execute
@@ -144,9 +143,13 @@ jobs:
       - name: Careful
         if: success() || failure()
         run: cargo +${{ env.RUST_NIGHTLY }} careful nextest run --all-features --workspace --color always --target ${{ matrix.target }}
-      - name: Miri
-        if: success() || failure()
-        run: cargo +${{ env.RUST_NIGHTLY }} miri test --all-features --workspace
+
+# We disable Miri since it is not actually able to test any of the app's unsafe code, since the
+# unsafe code is around I/O and Miri can't do I/O
+#
+#      - name: Miri
+#        if: success() || failure()
+#        run: cargo +${{ env.RUST_NIGHTLY }} miri test --all-features --workspace
 
   mutation-testing:
     if: github.event_name == 'pull_request'
